coverage:
  precision: 1
  round: down
  range: "50...80"
  status:
    project:
      default:
        # Do not fail PRs if the code coverage drops.
        target: 0%
        threshold: 0%
        base: auto

ignore:
  - "alaska/tests/*”
  - "alaska/_version.py"
